# Generated by Django 5.2.1 on 2025-05-31 13:05

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(validators=[posts.validators.BadWordsValidator(bad_words=['fuck', 'shit', 'ass', 'vagina'])])),
                ('author', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('programming_language', models.CharField(choices=[('py', 'Python'), ('php', 'PHP'), ('Java', 'Java'), ('js', 'JavaScript'), ('C#', 'C#'), ('C++', 'C++'), ('R', 'Ruby'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
    ]
